services:
  db:
    image: postgres:15
    container_name: forum-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forum_user
      POSTGRES_PASSWORD: forum_pass
      POSTGRES_DB: forum
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - internal

  api:
    build: ./apps/api
    container_name: forum-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - ./apps/api/.env
    networks:
      - internal

  thread:
    build: ./apps/thread
    container_name: forum-thread
    ports:
      - "80:80"
    depends_on:
      - api
    env_file:
      - ./apps/thread/.env
    networks:
      - internal

  sender:
    build: ./apps/sender
    container_name: forum-sender
    ports:
      - "8080:8080"
    depends_on:
      - api
    env_file:
      - ./apps/sender/.env
    networks:
      - internal

volumes:
  db_data:

networks:
  internal:
    driver: bridge
