name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Upgrade npm
        run: npm install -g npm

      - name: Install dependencies
        run: |
          npm cache clean --force
          npm install

      - name: Lint
        run: npm run lint

      - name: Test
        run: cd ./apps/api && npm install && npm run test

  docker:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set lowercase image prefix
        id: vars
        run: |
          REPO="${GITHUB_REPOSITORY,,}"
          echo "image_prefix=ghcr.io/${REPO}" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push API
        run: |
          docker build -t ${{ steps.vars.outputs.image_prefix }}-api:${{ steps.vars.outputs.short_sha }} ./apps/api
          docker push ${{ steps.vars.outputs.image_prefix }}-api:${{ steps.vars.outputs.short_sha }}

      - name: Build & Push Thread
        run: |
          docker build -t ${{ steps.vars.outputs.image_prefix }}-thread:${{ steps.vars.outputs.short_sha }} ./apps/thread
          docker push ${{ steps.vars.outputs.image_prefix }}-thread:${{ steps.vars.outputs.short_sha }}

      - name: Build & Push Sender
        run: |
          docker build -t ${{ steps.vars.outputs.image_prefix }}-sender:${{ steps.vars.outputs.short_sha }} ./apps/sender
          docker push ${{ steps.vars.outputs.image_prefix }}-sender:${{ steps.vars.outputs.short_sha }}
  